### ISSUE TITLE
Confusing error message if xml file is empty

### ISSUE THREAD

**Issue by oxve** [DataDog/datadog-ci#1015]
### Bug description

If I try to upload an xml file with an empty root node (see example) I get the following error message: \
`Invalid jUnitXML file [path/to/file.xml]: Neither <testsuites> nor <testsuite> are the root tag.`

The error message is confusing because it implies that the xml file is not correctly formatted, which it is not.

Example xml file

### Describe what you expected

The xml file to still be uploaded, or at least a more sensible error message.

### Steps to reproduce the issue

Run `datadog-ci junit upload path/to/file.xml` with `file.xml` containing:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="0" failures="0" disabled="0" errors="0" time="0.001" timestamp="2023-07-09T13:16:33.855" name="AllTests">
</testsuites>
```

### Additional context

ubuntu 22.04
datadog-ci version: https://github.com/DataDog/datadog-ci/releases/download/v2.18.0/datadog-ci_linux-x64

The npm package has the same issue.

### Command

junit

**Comment by juan-fernandez** [comment]
hey @oxve , thanks for the report. If the report were actually uploaded: what would you expect to see in datadog? Given that the report is "empty" (no tests were run)
