### ISSUE TITLE
Upgrade dependencies to fix downstream type conflict

### ISSUE THREAD

**Issue by devm33** [DataDog/datadog-ci#1059]
### Bug description

Hello 👋 Please consider upgrading dependencies [`@google-cloud/logging`](https://www.npmjs.com/package/@google-cloud/logging) and [`@google-cloud/run`](https://www.npmjs.com/package/@google-cloud/run). Both have newer version available that upgrade their dependency on [`google-gax`](https://www.npmjs.com/package/google-gax) to fix this issue, see https://github.com/googleapis/gax-nodejs/issues/1463
https://github.com/googleapis/gax-nodejs/releases/tag/v4.0.1

### Additional context

See also https://github.com/isaacs/rimraf/issues/264 for additional context

### Command

None

**Comment by ahellam** [comment]
Agreed. This is a blocker for dealing with a vulnerable version of protobufjs
