### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by dustinsmith1024** [DataDog/datadog-ci#106]
**Describe what happened**

Our tests are passing in the DD UI but we just get timeouts reporting back locally. Any thoughts?

We do have http errors in our UI test, but those don't matter for the test and it shows as successful in the DD UI.

**Steps to reproduce the issue:**

➜  mono git:(develop) ✗ npx datadog-ci synthetics run-tests -s 'tag:dustin-test' --apiKey <xxx> --appKey <xxx>
[buu-nfr-szr] Trigger test "Admin - Magic login"
[buu-nfr-szr] Waiting results for "Admin - Magic login"

=== REPORT ===
Took 122159ms

⇢ [buu-nfr-szr][NON-BLOCKING] | Admin - Magic login
  ✖ location: N. California (AWS) - device: chrome.laptop_large
    ⎋ result url: https://app.datadoghq.com/synthetics/details/buu-nfr-szr/result/1954206248458252575
    ✖ | Timeout

**Expected behaviour:**

Passing results

**Actual behaviour:**

Timeouts

**Additional context**
 - Mac OS
 - Node: v14.13.0

DD versions:
```
├─┬ @datadog/datadog-ci@0.7.1
│ ├─┬ datadog-metrics@0.8.1 (git+https://github.com/DataDog/node-datadog-metrics.git#12d16a80ea2a8846c91d80f5e127fb7b81b9f347)
```

**Comment by dustinsmith1024** [comment]
We up'ed the timeout and the issue went away.

**Comment by ricardo-cn** [comment]
I am actually having the same issue. 

I tried setting `longpollingTimeout`, but it does not do any difference. The weird thing is that if I go to Datadog's dashboard for the CI batch runs, they are all listed as "failed". However, if I go to the individual test run results, they are all showing as passed.

<img width="2378" alt="Screen Shot 2023-03-01 at 4 00 49 PM" src="https://user-images.githubusercontent.com/100245890/222294993-38f2b35a-bbac-4176-b769-a4f91288eeb8.png">

<img width="2380" alt="Screen Shot 2023-03-01 at 4 00 53 PM" src="https://user-images.githubusercontent.com/100245890/222295000-ccc8cfc5-df14-406c-a664-54ecba2156bc.png">

**Comment by lefebvree** [comment]
Hello @ricardo-cn,

The option to set the [Batch timeout](https://docs.datadoghq.com/continuous_testing/troubleshooting/#terminology) is `pollingTimeout`. When this timeout is reached and tests are still in progress the default behavior is to fail the batch, however the tests may finish and succeed after.
You can change this behavior by setting the `failOnTimeout` option to `false`.

You should also be able to check if this is what is happening in your case from the datadog-ci command output, or when clicking on a failed test batch in the interface.
