### ISSUE TITLE
Inconsistent documentation for upload source maps

### ISSUE THREAD

**Issue by nathanpower** [DataDog/datadog-ci#1080]
The [documentation](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps) for `sourcemaps upload` indicates that _only_ source maps are uploaded, and that the actual JS bundles should be be available via `minified-path-prefix`. 

The [readme](https://github.com/DataDog/datadog-ci/blob/master/src/commands/sourcemaps/README.md#upload) in this repo indicates that _both_ source maps and minified JS are uploaded.

I believe the former is true, but it would be good to have confirmation, and for both docs to be consistent with behaviour.

Thanks!

**Comment by BenoitZugmeyer** [comment]
Thank you for your feedback. The [documentation states](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs#upload-your-source-maps):

> The best way to upload source maps is to add an extra step in your CI pipeline and run the dedicated command from the Datadog CLI. It scans the `dist` directory and subdirectories to automatically upload source maps with relevant minified files.

So it looks like both documentation sources are accurate, and minified JS are indeed uploaded.

Could you give more details (a link and/or a direct documentation quote) on where you see that "only source maps are uploaded, and that the actual JS bundles should be be available via minified-path-prefix."?

**Comment by nathanpower** [comment]
Ah! Missed that bit

> Could you give more details (a link and/or a direct documentation quote) on where you see that "only source maps are uploaded, and that the actual JS bundles should be be available via minified-path-prefix."?

This part implied to me that the minified bundles needed to be accessible from the host:

> By running the command against the example dist directory, Datadog expects your server or CDN to deliver the JavaScript files at https://hostname.com/static/js/javascript.364758.min.js and https://hostname.com/static/js/subdirectory/javascript.464388.min.js.

I am currently battling a situation when I have two projects, one accessible only by VPN and on accessible publicly. 

For both, the upload works well in CI, but only the public one gets unminified code displayed in Datadog error tracking. This led me to believe that minified bundles must be accessible from the host, but perhaps the problem lies elsewhere.

**Comment by nathanpower** [comment]
When `sourcemaps upload` completes on CI the output reads:

<img width="472" alt="Screenshot 2023-10-07 at 14 38 19" src="https://github.com/DataDog/datadog-ci/assets/13329684/643cc5df-0bb0-490f-b4a0-0e8cf64a1835">

This is also the count of `*.js.map` files in the directory - total for `*.js` plus `.js.map` would be 186

So it does at least appear from the output that only the maps are uploaded?

**Comment by nathanpower** [comment]
> So it does at least appear from the output that only the maps are uploaded?

Reading the code I can see that both maps and minified files are added as file streams - I'll close this one and open something more specific if it turns out the bug is not on our side.
