### ISSUE TITLE
Still missing code snippets after uploading the source maps from a Flutter web app

### ISSUE THREAD

**Issue by Gummiees** [DataDog/datadog-ci#1171]
### Bug description

First off, I'm not sure if JS source maps from a Flutter web are even supported on Datadog. If not, this should rather be an enhancement. If this is a bug, it would be nice to have somewhere documented how to do this whole process for a Flutter web app.

On the document ["Flutter Crash Reporting and Error Tracking"](https://docs.datadoghq.com/real_user_monitoring/error_tracking/flutter/#upload-symbol-files-to-datadog) one would expect to find this information, however there you can only find information related to Flutter mobile apps, [since you cannot get symbol files for web](https://docs.flutter.dev/deployment/obfuscate#supported-targets). So instead I followed ["Upload JavaScript Source Maps"](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs).

After uploading the source maps with the correct service name and version, I was able to see them uploaded:

<details>
<summary>Screenshot</summary>

![Screenshot 2024-02-05 at 14 59 38](https://github.com/DataDog/datadog-ci/assets/18721359/fbe51332-af34-4125-8b28-11a25056601d)

I have to say that it would be nice being able to both remove the source maps manually from that view and to force rewrite using `datadog-ci`.

</details>

Still after the source map for `main.dart.js` was successfully uploaded, the error traces are not helpful. Here are some examples.

<details>
<summary>Unminification failed</summary>

Here it points to `privacy_policy_screen.dart` correctly, but does not show the code which caused this issue, and shows files which are noise at the beginning.

![Screenshot 2024-02-05 at 15 08 11](https://github.com/DataDog/datadog-ci/assets/18721359/dbb872cf-336a-44dd-9873-5adbe03be369)

</details>

<details>
<summary>Missing code snippet</summary>

Not sure how this error was caused, but I cannot get any help from the error trace neither. It has both the unminification failed error and missing code snippet error. The evaluation error still has the minified code version (`d.apply(null,B)`).

![Screenshot 2024-02-05 at 15 13 55](https://github.com/DataDog/datadog-ci/assets/18721359/0b00acdf-385d-445c-9db7-b27ffb79a11a)

</details>

This does not happen with all the error traces. There are some that work as intended, the line which caused the error does not appear as the first line, but if you scroll down you can find the original file and even the source code if the git integration has been set up.

<details>
<summary>Extra links to the Flutter source maps</summary>

- [dart2js source map extensions](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/doc/sourcemap_extensions.md#source-map-extensions)
- [Source map v3](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.n05z8dfyl3yh)
- [Official Dart library to "parse, inspect, and manipulate stack traces produced by the underlying Dart implementation"](https://pub.dev/packages/stack_trace)
- [Flutter tracking issue related to incomplete source maps](https://github.com/flutter/flutter/issues/87734)
</details>

### Describe what you expected

1. To see readable and useful error stack traces, pointing to the right files
2. To see the line on the code which caused this issue
3. To have GitHub linked

### Steps to reproduce the issue

1. Have a Flutter web app with RUM configured and generate some errors
2. Build the app with source maps (`flutter build web --source-maps`)
3. [Upload the JS source maps following the official docs](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs), example:
```sh
datadog-ci sourcemaps upload build/web --service=<SERVICE_NAME> --release-version=<VERSION> --minified-path-prefix=<URL>
```

### Additional context

- Macbook Pro | Apple M1 | 14.2.1 (23C71)
- Flutter 3.16.9
- datadog-ci 2.29.0

### Command

sourcemaps

**Comment by fuzzybinary** [comment]
Hi @Gummiees ,

I'll double check the documentation as it is likely out of date or potentially in the wrong place, but the `flutter-symbols upload` command should properly upload JavaScript source maps (despite the confusing name).

Can you try adding `--web-sourcemaps` and `--minified-path-prefix` to your symbols upload command for Flutter and see if that fixes your issue?

**Comment by Gummiees** [comment]
> Hi @Gummiees ,
> 
> I'll double check the documentation as it is likely out of date or potentially in the wrong place, but the `flutter-symbols upload` command should properly upload JavaScript source maps (despite the confusing name).
> 
> Can you try adding `--web-sourcemaps` and `--minified-path-prefix` to your symbols upload command for Flutter and see if that fixes your issue?

Oh dang it, I completely missed that option, sorry about that.

I have now uploaded the source maps using `flutter-symbols upload` instead, will need a bit of time to gather some errors and see if this has changed.

Thanks for your help and quick feedback!

**Comment by Gummiees** [comment]
After some quick testing it would seem like the same issue still persists:

![Screenshot 2024-02-05 at 17 14 06](https://github.com/DataDog/datadog-ci/assets/18721359/30cf1ff6-9bfb-49bd-8093-6a02ec812345)

However, I've realised that we're doing something wrong, which will take a while for us to fix, which is updating the version for each deployment we do.

This will take us a while, since we deploy to staging every time we push something to `master`, but we don't update the versions until it gets to production. We have to, for instance, use the commit hash as version for RUM so we can upload the source maps automatically too when building the web during the CI.

This could be the cause, as we are not sending the source maps for the latest build since the version is not getting updated. That's the reason why personally would love to be able to rewrite the source maps stored on Datadog, but for now that's a me problem 😄

I will close the issue until we get that sorted. If the issue persists afterward, I will create a new one with similar info 👍 thanks!
