### ISSUE TITLE
`USE_HERMES` environment variable is not respected when used in the `react-native xcode` command

### ISSUE THREAD

**Issue by FrikkieSnyman** [DataDog/datadog-ci#1189]
Hi, 

I came across this while integrating the Datadog SDK to our React Native project, which is currently using react-native v0.70.13.

We have not yet enabled Hermes for our iOS app, and hence, we set the `USE_HERMES` environment variable to `false`. 

However, accessing this environment variable in Node via `process.env.USE_HERMES` returns a string, and not a boolean. Hence, the check being done in `shouldComposeHermesSourcemaps`:

```
if (process.env.USE_HERMES) {
    return true;
}
```

is naive, since `process.env.USE_HERMES` being the string `"false"` would have the check be evaluated to true.

I've created the following change as a patch in our codebase: https://github.com/FrikkieSnyman/datadog-ci/commit/934e74901b923e13141bf1cdcec5279b54c69997

I would be happy to submit a PR for this too, but adhering to your guidelines, I'll open an issue first.

**Comment by louiszawadzki** [comment]
Hi @FrikkieSnyman, thanks for reaching out!

Indeed your fix seems good! 
I believe you're good to open a PR, let me know if you want to write the unit tests yourself, otherwise I can take care of it :)

**Comment by FrikkieSnyman** [comment]
@louiszawadzki Thanks - it would be appreciated if you can take care of the tests. I'm not able to take the time to set up this repo locally!
