### ISSUE TITLE
v2.38 on npm still references ws@7.4.6

### ISSUE THREAD

**Issue by shank-eric** [DataDog/datadog-ci#1349]
### Bug description

I can see the tag for v2.38.0 has ws bumped up to ^7.5.10, but I'm not seeing that come through in what's published to npm.  When I check the [Code tab](https://www.npmjs.com/package/@datadog/datadog-ci?activeTab=code) on npm it still has 7.4.6 and I see the same in my local node_modules folder after installing the new version

### Command

None

**Comment by Drarig29** [comment]
Hi @shank-eric!

Looks like we made a mistake when releasing...

I'll release a `v2.38.1` tomorrow. Sorry for the inconvenience!

**Comment by shank-eric** [comment]
no worries, thanks for the update! :)

**Comment by Drarig29** [comment]
This should now be fixed 👍

**Comment by shank-eric** [comment]
I see the new version now, thanks for the quick fix!
