### ISSUE TITLE
v2.38 for darwin-x64

### ISSUE THREAD

**Issue by rodrigopequeno** [DataDog/datadog-ci#1351]
### Bug description

The latest version does not support for darwin-x64, is this expected?

### Describe what you expected

Support for darwin-x64

### Steps to reproduce the issue

Not applicable

### Command

None

**Comment by rodrigopequeno** [comment]
#1348 identified

Closing

**Comment by Drarig29** [comment]
Yes, a mistake on our side. Sorry for the inconvenience

**Comment by Drarig29** [comment]
This should now be fixed 👍
