### ISSUE TITLE
Standalone binary url returns 404

### ISSUE THREAD

**Issue by tudorsirbu** [DataDog/datadog-ci#1352]
### Bug description

When trying to download the standalone binary the url returns 404

<img width="597" alt="Screenshot 2024-06-19 at 10 02 55" src="https://github.com/DataDog/datadog-ci/assets/6299690/b691f871-4e01-4cc5-a923-15bab892d6e5">

### Steps to reproduce the issue

 curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_darwin-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci

### Additional context

- macOS 14.5

### Command

None

**Comment by Drarig29** [comment]
Hi! Sorry, this will be fixed in next patch release: https://github.com/DataDog/datadog-ci/pull/1348

**Comment by Drarig29** [comment]
This should now be fixed 👍
