### ISSUE TITLE
Uploaded source maps does not work if version contains an uppercase letter

### ISSUE THREAD

**Issue by dtinth** [DataDog/datadog-ci#140]
**Describe what happened**
We at @taskworld are currently migrating to Datadog RUM from other monitoring services. Due to legacy reasons, our version specifiers contain an uppercase letter. This works for the most part, except source maps.

**Steps to reproduce the issue:**
1. Configure Datadog RUM with a version number with uppercase letter in it. [Due to versions in Datadog being tags, they get converted into lowercase.](https://docs.datadoghq.com/getting_started/tagging/)
2. Upload source map with `--release-version=1234-SNAPSHOT`.
3. Cause an error in the application and inspect in Datadog.

**Expected behaviour:**
2. `datadog-ci` should convert `--release-version` to lowercase just like how Datadog ingests data.
3. The error should have proper sourcemap.

**Actual behaviour:**
2. `datadog-ci` sends the `--release-version` with uppercase and **and version matching is case sensitive**.
3. The error does not have a sourcemap.

**Additional context**
Possible workaround is to just call the `datadog-ci` command with lowercased version number (`--release-version=1234-snapshot`). However I strongly believe that either `datadog-ci` should also lowercase this version specifier, or when matching the sourcemap, versions should be matched case-insensitively.

**Comment by lraucy** [comment]
Hello @dtinth, thank you for reporting! Indeed that's a bug on our side, you should not have to bother about this when making the datadog-ci call, the conversion into lowercase should be done automatically instead. We'll release a fix in the backend early next week. Already uploaded sourcemaps won't be fixed, but it will work with new uploads.

In the meantime if you want to make it work you'll have to use the workaround you mentioned.

**Comment by dtinth** [comment]
@lraucy We are currently using the aforementioned workaround, and it works with no issues. Thanks for a quick response! 😃

**Comment by lraucy** [comment]
We released the change in the backend: the workaround should not be necessary anymore for newly-uploaded sourcemaps. I'm closing the issue, thank you again for the bug report!

**Comment by dtinth** [comment]
@lraucy That was very speedy, thank you!
