### ISSUE TITLE
Deprecated cli warning log

### ISSUE THREAD

**Issue by filipStoklasa23** [DataDog/datadog-ci#1424]
### Bug description

When I run datadog cli in pipeline I keep getting pollingTimeout deprecation warning even though it is not configured in the script.

`npm warn exec The following package was not found and will be installed: @datadog/datadog-ci@2.42.0
The 'pollingTimeout' property is deprecated. Please use 'batchTimeout' instead.
If both 'pollingTimeout' and 'batchTimeout' properties exist, 'batchTimeout' is used!`

### Describe what you expected

I would expect the log not to appear If I define batchTimeout in the script

### Steps to reproduce the issue

Run:
`npx -p @datadog/datadog-ci@2.42.0 datadog-ci synthetics run-tests ... --batchTimeout 12000`

### Additional context

- CLI version - 2.42.0

### Command

synthetics

**Comment by Drarig29** [comment]
Hi @filipStoklasa23! We added a card in our backlog. For now, you can simply ignore that warning.

**Comment by Drarig29** [comment]
Hi! We merged a fix and it will be available in the next release!

**Comment by filipStoklasa23** [comment]
Thank you so much!
