### ISSUE TITLE
Step Function context is not injected into lambda payload

### ISSUE THREAD

**Issue by brainsiq** [DataDog/datadog-ci#1429]
### Bug description

With a trivial step function definition containing only a single Lambda task, running the instrument command with propagate/merge flags does not result in any update of the Lambda payload in the definition.

### Describe what you expected

Payload should be replaced with `States.JsonMerge($$, $, false)`

### Steps to reproduce the issue

Example step function ASL:

```
{
  "Comment": "An example step function",
  "StartAt": "ExampleLambda",
  "States": {
    "ExampleLambda": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "OutputPath": "$.Payload",
      "Parameters": {
        "Payload.$": "$",
        "FunctionName": "arn:aws:lambda:{region}:{account}:function:{name}:{alias}"
      },
      "End": true
    }
  }
}
```

Command:

```
datadog-ci stepfunctions instrument \
  --step-function {function-arn} \
  --forwarder {forwarder-arn} \
  --propagate-upstream-trace \
  -mlt
```

### Additional context

OS: Mac OS Sonoma
Node version: 20
Datadog-CI version: 2.42.0

### Command

stepfunctions instrument

**Comment by nine5two7** [comment]
@brainsiq It is expected to inject execution context in the payload when the Step Function invokes either Lambda or another Step Function. We are currently working on a fix for the CI.
