### ISSUE TITLE
Error installing @datadog/datadog-ci

### ISSUE THREAD

**Issue by victorwhy** [DataDog/datadog-ci#1493]
### Bug description

Hi,

I'm on node version 20.12 (as is our build pipeline), and running this command:

```
npm install -g @datadog/datadog-ci
```

results in this error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @smithy/node-config-provider@^3.1.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Describe what you expected

That datadog-ci is installed without failling.

### Steps to reproduce the issue

On node version 20.12, run `npm install -g @datadog/datadog-ci`

### Additional context

- MacOS 14.2.1 (23C71)
- Node: 20.12.0
- npm 10.5.0

Looks like this was updated very recently, so maybe thats why? but wondering why this is pointing at a version that's not fully available yet?

https://www.npmjs.com/package/@smithy/node-config-provider

### Command

None

**Comment by Drarig29** [comment]
Hi @victorwhy!

You should report this to AWS, this is likely an issue with their upgrading system: a dependant package was probably published before its dependency. Does it work now?

**Comment by victorwhy** [comment]
> Hi [@victorwhy](https://github.com/victorwhy)!
> 
> You should report this to AWS, this is likely an issue with their upgrading system: a dependant package was probably published before its dependency. Does it work now?

yeah! it resolved itself - 100% what you described, although it was only happening when installing this dependency
