### ISSUE TITLE
Upload *.js minified files

### ISSUE THREAD

**Issue by everton-nasc** [DataDog/datadog-ci#165]
**Is your feature request related to a problem? Please describe:**
Based on the datadog-ci documentation, during the upload we need to upload our `*.map` along with the minified files `*.min.js`.
Ref: 
```php
Note: Currently only source maps with the .min.js extension will work to correctly unminify stack traces in the Error Tracking UI. Source maps with other extensions (for example, .mjs, etc.) while accepted will not unminify stack traces.
```
[Here](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs)

The project that I'm working, we're minifying the files and saving it as a `*.js` suffix instead `*min.js`. Seems after the project build, the datadog cannot unminify properly the error. 

**Describe the solution you'd like:**
--> Accept minified files with different file suffix: e.g. `minifiedJsFile.js` instead `minifiedJsFile.min.js`
Will be nice to have an option to accept files with `*.js` suffix (file that we already know that were previous minified).

**Comment by lraucy** [comment]
Hey @everton-nasc about that one, the documentation is actually incorrect. `<filename>.js` + `<filename>.js.map` are accepted, no need for the `.min.js` suffix. We just fixed the documentation.


Still, if the unminification is not working, it means there is something wrong going on. Could you open a support ticket? We'll ask you more details about your setup to understand where this comes from.

**Comment by everton-nasc** [comment]
Thanks for your feedback and fix the documentation @lraucy.
I'll open a support ticket in order to investigate this issue.
