### ISSUE TITLE
Use the `file` attribute in source map when available (or as fallback)

### ISSUE THREAD

**Issue by gustavkj** [DataDog/datadog-ci#187]
**Describe what happened**
My main output file is `app.js`, for some reason `SourceMapDevToolPlugin` calls the main output file `main` regardless of the configured output name.

Since `datadog-ci` tries to create the filename by removing the `map` extension, I get the following error:

```
❌ Failed upload sourcemap for [build/app/server/main.js.map]: Missing corresponding JS file for sourcemap (build/app/server/main.js)
```

**Steps to reproduce the issue:**
1. Set [`output.filename`](https://webpack.js.org/concepts/output/#usage) in the `webpack.config.js` file to e.g. `app.js`. 
2. Configure `SourceMapDevToolPlugin` as per the instructions in the [Datadog documentation](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs).

**Expected behaviour:**
If the `file` attribute is present in the source map, then that value should be used. Otherwise, it can fallback to the current logic.

Optionally, the other way around since file system operations might slow it down.

**Actual behaviour:**

Fails if the source map and generated file do not share the same name.

**Additional context**
 - [Source map specification proposal](https://sourcemaps.info/spec.html)

**Comment by jybp** [comment]
Hey @gustavkj !
Thanks for opening this issue. We are not currently looking at the 'file' attribute indeed. It is something that we are planning to support at some point. Unfortunately I don't have an estimate date to share for now.

**Comment by gustavkj** [comment]
@jybp Thank you! Just to check, would it need changing in other places than this repo to make it work?

If not, I can make a PR. I guess the best would be to make the `file` attribute a fallback to the current logic. What do you say?

**Comment by jybp** [comment]
> Just to check, would it need changing in other places than this repo to make it work?

@gustavkj I don't think it would. You can go ahead and make a PR, but just to be 100% transparent, it probably won't be merged any time soon. There is a high change it will conflict with other changes we're not yet ready to introduce. 
Nothing prevents you from using your custom version of datadog-ci to unblock you in the meantime.

> I guess the best would be to make the file attribute a fallback to the current logic.

It probably is the right thing to do as it won't introduce a breaking change for some setups.

**Comment by jybp** [comment]
> There is a high change it will conflict with other changes we're not yet ready to introduce.

Just to clear up any confusion, I was talking about this particular pull request: https://github.com/DataDog/datadog-ci/pull/136

**Comment by gustavkj** [comment]
I'm closing this. I think we were trying to use this incorrectly. We were trying to use this to push source maps for transpiled server-side code, which I gather is not the intension of this tool. 

To solve our problem, we started using the [`--enable-source-maps`](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_enable_source_maps) flag. This way the original code location is added to stack traces.
