### ISSUE TITLE
Sourcemaps do not appear to be useable with React stacktraces

### ISSUE THREAD

**Issue by g-dx** [DataDog/datadog-ci#272]
**Describe what happened**

The RUM SDK uploaded an error to Datadog but the stacktrace was not un-minified even though sourcemaps were successfully uploaded _before_ the error occurred.

**Steps to reproduce the issue:**

The following stacktrace was observed in one of our React webapps which has the RUM SDK configured:

```
TypeError: Cannot read property 'textKey' of undefined
at Xi @ https://<host>/static/js/main.5d9b18c8.chunk.js:1:148419
at Zo @ https://<host>/static/js/2.963f137f.chunk.js:2:846898
at wu @ https://<host>/static/js/2.963f137f.chunk.js:2:893128
at gs @ https://<host>/static/js/2.963f137f.chunk.js:2:885855
at vs @ https://<host>/static/js/2.963f137f.chunk.js:2:885780
at us @ https://<host>/static/js/2.963f137f.chunk.js:2:882789
at <anonymous> @ https://<host>/static/js/2.963f137f.chunk.js:2:834160
at t.unstable_runWithPriority @ https://<host>/static/js/2.963f137f.chunk.js:2:909561
at $i @ https://<host>/static/js/2.963f137f.chunk.js:2:833869
at Qi @ https://<host>/static/js/2.963f137f.chunk.js:2:834105
```
Before this error occurred sourcemaps had been uploaded as follows:

```
g-dx@xps:~ ./upload-sourcemaps.sh
Starting upload with concurrency 20.
Will look for sourcemaps in build
Will match JS files for errors on files starting with https://<host>/
version: 41deb68e service: our-webapp project path:
Uploading sourcemap build/static/js/2.963f137f.chunk.js.map for JS file available at https://<host>/static/js/2.963f137f.chunk.js
Uploading sourcemap build/static/js/main.5d9b18c8.chunk.js.map for JS file available at https://<host>/static/js/main.5d9b18c8.chunk.js
Uploading sourcemap build/static/js/runtime-main.19cb0810.js.map for JS file available at https://<host>/static/js/runtime-main.19cb0810.js

Command summary:
✅ Uploaded 3 sourcemaps in 6.596 seconds.
```
(`datadog-ci` is version `0.13.2`)

**Expected behaviour:**

I would expect to see similar output to my Firefox + React devtools console output which is as follows:

![console](https://user-images.githubusercontent.com/4189306/121773189-1bea9200-cb72-11eb-8956-5ee36f753f5c.png)

**Actual behaviour:**

Datadog does not un-minify the stacktrace:

![dd](https://user-images.githubusercontent.com/4189306/121773276-c6fb4b80-cb72-11eb-9837-0ae95d3ea2dc.png)

Does the Datadog server-side stacktrace parsing understand React stacktraces which include minified component names? Is there some other step I am missing here?

**Additional context**
- `@datadog/browser-rum` is version `2.12.1`

**Comment by jybp** [comment]
Hey @g-dx 
Thanks for sharing screenshots. I'm not seeing any obvious issue.
Are the service and version attached to RUM events in DataDog the correct ones (`our-webapp`/`41deb68e`) ? It should be displayed right above `Parent Hierarchy`.

Could you open a support ticket? We'll ask you more details about your setup to understand where this comes from.

**Comment by g-dx** [comment]
Hey @jybp 

Thanks for coming back to me so quickly. I've discovered that as we are using [react-app-rewired](https://github.com/timarney/react-app-rewired) our JS sourcemaps may contain invalid or unresolvable entries. I'll look to get this fixed first before opening anything with support.

Thanks again.

**Comment by jybp** [comment]
@g-dx OK, I'll close the issue in the meantime. Do not hesitate to open a support ticket.

**Comment by g-dx** [comment]
To help anyone else who runs into this issue:

The problem we had was that by default React logs all uncaught errors using `console.error(...)` which results in a RUM error of type `console`. The Datadog docs do not make this clear but sourcemap un-minification **_only works_** with `source` or `custom` type RUM errors.
