### ISSUE TITLE
Proxy issue when using HTTP Proxy to push sourcemap to datadog

### ISSUE THREAD

**Issue by fischaz** [DataDog/datadog-ci#292]
**Describe what happened**

When using datadog-ci to push the sourcemap from our build server to datadog via our internal web proxy (squid), the upload fails with the error below.

The same command works from a laptop removing the proxy information.

**Steps to reproduce the issue:**
- setup a HTTP proxy (like squid) to listen on HTTP port (3128)
- allow 'CONNECT' only through the proxy to HTTPS port (443)
- set environment variable HTTPS_PROXY=http://myproxy:3128
- execute datadog-ci sourcemap upload

**Expected behaviour:**
📝the sourcemap initiates a TCP Connection to the proxy
-  sends `CONNECT sourcemap-intake.datadoghq.com:443 HTTP/1.1` to the proxy
- proxy allows connection (TLS is negotiated between local app and datadog endpoint)
- datadog-ci uploads sourcemap items correctly

**Actual behaviour:**
📝The operation fails in datadog-ci

```
> @ dd-sourcemap-upload /build
> datadog-ci sourcemaps upload ./public/dist --minified-path-prefix=/dist --disable-git "--service=myapp" "--release-version=5.feat-test-no-a-bf375d71f.17"

Starting upload with concurrency 20. 
Will look for sourcemaps in public/dist
Will match JS files for errors on files starting with /dist
version: 5.feat-test-no-a-bf375d71f.17 service: myapp project path: 
Uploading sourcemap public/dist/admin/xxx.js.map for JS file available at /dist/admin/xxx.js
Uploading sourcemap public/dist/datadog.js.map for JS file available at /dist/datadog.js
Uploading sourcemap public/dist/globalLibs.js.map for JS file available at /dist/globalLibs.js
Uploading sourcemap public/dist/header.js.map for JS file available at /dist/header.js
Uploading sourcemap public/dist/reports/xxx.js.map for JS file available at /dist/reports/xxx.js
Uploading sourcemap public/dist/reports/xxx.js.map for JS file available at /dist/reports/xxx.js
Uploading sourcemap public/dist/reports/xxx.js.map for JS file available at /dist/reports/xxx.js
Uploading sourcemap public/dist/user/xxx.js.map for JS file available at /dist/user/xxx.js
Uploading sourcemap public/dist/user/xxx.js.map for JS file available at /dist/user/xxx.js
Uploading sourcemap public/dist/user/xxx.js.map for JS file available at /dist/user/xxx.js
❌ Configuration error: Error: DATADOG_API_KEY does not contain a valid API key for Datadog site datadoghq.com.
❌ Failed upload sourcemap for [public/dist/header.js.map]: Error: write ECONNRESET
WARN: Error: Could not flush metrics to api.datadoghq.com: Error: connect ETIMEDOUT 3.233.147.157:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dd-sourcemap-upload: `datadog-ci sourcemaps upload ./public/dist --minified-path-prefix=/dist --disable-git "--service=myapp" "--release-version=5.feat-test-no-a-bf375d71f.17"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dd-sourcemap-upload script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T06_12_48_121Z-debug.log
```

And the PROXY Logs show unexpected attempt to connect to a HTTP website:
```
POST https://sourcemap-intake.datadoghq.com/v1/input HTTP/1.1
```
which is denied by the proxy policy and wouldn't work anyway.

**Additional context**
 - running in docker containers from image `node:14.16.1-buster-slim` as base

 - an explanation of what might cause the bug and/or how it can be fixed

The issue really is just an `axios` issue already reported in https://github.com/axios/axios/issues/3384 but as a paying datadog customer, I wanted to bring it to the attention of the datadog support team to see if they could do a workaround like possibly changing the 'axios' http module to something else.

Internally, as this is a docker image, I've manually *patched* the http.js file in axios to let it understand my HTTP proxy (see patch attached), although I doubt this patch is good for **all** cases....

**Comment by lraucy** [comment]
Hi @fischaz! Thank your for reporting, I'll try to reproduce this.

I can't open your http.js.txt file though, are you sure you uploaded the correct file?

I see in [the discussion](axios/axios#3384) that several packages exist to fix this, did you test them or did you went directly for your fix of http.js?

**Comment by fischaz** [comment]
My bad @lraucy , saving didn't quite work... I should have checked better.... 

wondering if there is a way to delete that old file now 🤔 

[http.js.patch.txt](https://github.com/DataDog/datadog-ci/files/6794462/http.js.patch.txt)

Re the existing package to fix, I did try the `axios-https-proxy-fix` one, but it was not working with environment variable, but it inspired this patch. 

Basically, I think if I passed the proxy programmatically with the config object, it might have worked with that alternate package, but because I used environment variable, it was parsed, but never really replaced the agent in the config object in axios (order in code was not quite there).

**Comment by fischaz** [comment]
Not sure I should add to this issue or create a different issue... 

but there is a second HTTP Proxy bug during that run....

part of the sourcemaps upload in this code is using something call `getMetricsLogger` in `commands/sourcemaps/metrics.js`... 

this in turn use something called `BufferedMetricsLogger` from the npm module [datadog-metrics](https://www.npmjs.com/package/datadog-metrics)
and finally, this uses a module [dogapi](https://www.npmjs.com/package/dogapi)....

long story short, the dogapi module does not have any concept of proxy environment variable at all and uses the 'https' module. 

it allows the caller to programmatically set a 'agent' which can be a proxy agent via the `options.proxy_agent` parameter, which is passed transparently in `datadog-metrics` but is left alone in datadog-ci (not set at all, left to default agent). 

JUST in this case, I believe the best place for me to add that support was to patch dogapi to set an agent if not provided by the caller (explicit) but if the environment variable do exist (implicit):

See 
[dogapi_client.js.patch.txt](https://github.com/DataDog/datadog-ci/files/6929924/dogapi_client.js.patch.txt)

now I could raise a PR to the dogapi github repos... but that repos does not seem very active and is not even maintained by the official datadog team, so I wonder if this would ever get fixed (or if this would be the right place to fix that).

Anyhow, just adding to the general issue of datadog-ci proxy support 👍

**Comment by lraucy** [comment]
Latest version v0.16.1 includes changes for supporting `HTTPS_PROXY`env var. I'm closing this ticket, feel free to reopen if somehow this doesn't work for your setup
