### ISSUE TITLE
startUrl cannot be overridden using the URL environment variable

### ISSUE THREAD

**Issue by riisi** [DataDog/datadog-ci#294]
**Describe what happened**
The startUrl cannot be override by the `URL` environment variable.

**Steps to reproduce the issue:**
1. Create a browser test with a defined start URL
2. Run the tests with `URL=https://otherurl.com npx datadog-ci synthetics run-tests`

**Expected behaviour:**
1. The startUrl should be https://otherurl.com

**Actual behaviour:**
1. The startUrl is the original defined in the test.

**Additional context**
It looks like the input from process.env.URL is overriden here. https://github.com/DataDog/datadog-ci/blob/0aadc20f31653677cd4ac21ff1202a59317e0c88/src/commands/synthetics/utils.ts#L88

I was able to override using a different variable. 

```
{
  "datadogSite": "datadoghq.com",
  "files": "{,!(node_modules)/**/}*.synthetics.json",
  "global": {
    "deviceIds": ["laptop_large"],
    "executionRule": "blocking",
    "followRedirects": true,
    "locations": ["aws:us-east-1", "aws:eu-west-1"],
    "retry": {"count": 0, "interval": 300},
    "startUrl": "{{ANOTHER_VARIABLE_NOT_URL}}"
  },
  "pollingTimeout": 300000
}
```

This is confusing as the docs (at least in my reading) indicate that `{{URL}}` can be used to override. 
See src/commands/synthetics/README.md

**Comment by m-rousse** [comment]
Hi @riisi,
This is expected behavior: see https://github.com/DataDog/datadog-ci/issues/174#issuecomment-793532455
I'll see to update documentation to make it clearer.

**Comment by riisi** [comment]
Thanks, I must have read this 10 times and still didn't get it. 
I guess the environment variables that are set from the original URL are used

**Comment by m-rousse** [comment]
Yes, these environment variables are set from the original URL if you need to re-use parts of the URL to build the new one.

As an example, for a start URL of `http://prod.brand.tld/home?query`, with an override of `{{PROTOCOL}}//staging.{{DOMAIN}}/{{TEMPORARY_HASH}}/{{PATHNAME}}?{{PARAMS}}` you would rewrite the URL to `https://staging.brand.tld/a1b2c3d4/home?query` allowing to have one generic start URL for many different tests on different URLs.
(supposing the environment variable `TEMPORARY_HASH` is set to `a1b2c3d4`)

**Comment by riisi** [comment]
Ah I see. Thank you.
