### ISSUE TITLE
Publish a docker image

### ISSUE THREAD

**Issue by nhoughto** [DataDog/datadog-ci#296]
**Is your feature request related to a problem? Please describe:**
Be nice to be able to call this directly via a docker image rather than having to `npm install` or even having to repackage it ourselves.

**Describe the solution you'd like:**
Packaged as a docker image like `aws` https://hub.docker.com/r/amazon/aws-cli

**Comment by sdeprez** [comment]
👋  thanks for the reasonable suggestion, unfortunately it's not something that we will consider _at the moment_, but I'll leave the card open to gather feedbacks!

**Comment by lefebvree** [comment]
Hello, datadog-ci is now available as an image on Dockerhub: [`datadog/ci`](https://registry.hub.docker.com/r/datadog/ci) and GCR: [`gcr.io/datadoghq/ci`](https://console.cloud.google.com/gcr/images/datadoghq/GLOBAL/ci).
