### ISSUE TITLE
Enable Variable Overrides

### ISSUE THREAD

**Issue by ahosking** [DataDog/datadog-ci#326]
**Is your feature request related to a problem? Please describe:**
When attempting to upload a junit file from a system where there is no locally discovered git branch, there appears no good way to send a variable override to have the tests appear in the CI Dashboard.

**Describe the solution you'd like:**
I'd like to be able to use any of the variables found in the helper functions by passing them in with the upload.
For example: 
`DD_GIT_BRANCH`
`GIT_BRANCH`

**Describe alternatives you've considered:**
I've tried changing the test method to GITHUB and passing variables that way but this seems to adversely affect how the results are reported and displayed in the user interface.

**Additional context:**
The wall time varies wildly and in no service ever seems to be remotely correct.
![image](https://user-images.githubusercontent.com/1209293/129788019-8cc3c05d-4eb6-4849-9208-0c10066e03d2.png)

**Comment by edrevo** [comment]
@juan-fernandez, this was fixed in https://github.com/DataDog/datadog-ci/commit/8bef1e646f1023cd69e9e716ffb478d112d3c41d, right?

**Comment by juan-fernandez** [comment]
that's correct, `DD_GIT_BRANCH` is available as an environment variable to set the git branch. I'm closing the issue. Let me know if you have issues @ahosking. And Thanks Ximo for bumping this thread :)
