### ISSUE TITLE
Soucemap upload incorrectly searches for corresponding js files

### ISSUE THREAD

**Issue by vitkusv** [DataDog/datadog-ci#357]
**Describe what happened**

Getting this error when uploading sourcemaps:

>Failed upload sourcemap for [node/public/static/built/main.bbc34b813faf0278832c.js.map]: Missing corresponding JS file for sourcemap (node/public/static/built/main.bbc34b813faf0278832c.js)

For js files we're using **[contenthash]** for built js files and in SourceMapDevToolPlugin we're using **[fullhash]** per DataDog docs. 

**Steps to reproduce the issue:**
Webpack config has:

```javascript
output: {
        ...
        filename: '[name].[contenthash].js',
        ...
    },
```
```javascript
new webpack.SourceMapDevToolPlugin({
            noSources: false,
            filename: '[name].[fullhash].js.map',
}),
```

files produced:

- main.bbc34b813faf0278832c.js.map
- main.435bd1f3554ed5ac14e8.js

**Expected behaviour:**
js file is found even with a different hash

**Actual behaviour:**
The problem is that your cli finds a map file first and then checks for corresponding js file with the same hash, but with the .js extension only, but in reality these files have different hashes.

**Comment by lraucy** [comment]
Hi @vitkusv! Thank you for the bug report.

Indeed the suggestion of our documentation is not working in your case.

We should implement the suggested fix of [this issue](https://github.com/DataDog/datadog-ci/issues/187), which is to look at the sourcemap's field `file` which contains the path of the source file, rather than making the assumption sourcemap name is prefixed by the minified file path; this would probably fix your issue.

In the meantime, I can offer this workaround:


```diff
new webpack.SourceMapDevToolPlugin({
            noSources: false,
-           filename: '[name].[fullhash].js.map',
+           filename: '[file].map',
}),
```

This configuration should solve the problem by making sure the sourcemaps have the expected names.

**Comment by vitkusv** [comment]
Thanks, @lraucy! That did generate the right filenames! Though the problem now is that I still don't see real stack trace once the exception is being thrown. Is there a way to troubleshoot this from inside the DataDog web app?

Upload succeeded: ✅ Uploaded 10 sourcemaps in 1.896 seconds.

But getting this on the stack trace lines: 
![image](https://user-images.githubusercontent.com/59565657/133045222-92b8e18f-4ff8-4454-a32c-d39e84914ee0.png)

**Comment by lraucy** [comment]
Hey @vitkusv, glad it fixed it! I'll update the documentation.

There is no way of troubleshooting this from the web app (yet). Could you open a ticket to Datadog's support? We'll be able to look into this with more details.

**Comment by vitkusv** [comment]
Figured this one out also. Specified the full path in --minified-path-prefix:
```diff
- --minified-path-prefix=/static/built/
+ --minified-path-prefix=https://custom.my.company.com/static/built/
```
Though don't get the git repo links, but that's more than enough for now.
