### ISSUE TITLE
Request failed with status code 408

### ISSUE THREAD

**Issue by StreetStrider** [DataDog/datadog-ci#448]
**Describe what happened**
I'm using `datadog-ci sourcemaps` to upload sourcemaps for our datadog-assisted project. We have 49 sourcemap files of various sizes (from 4K to 29MB). When using default concurrency level when uploading maps I end up with the state when 39 files are loaded and 10 files are not. The error is `Request failed with status code 408 (Request Timeout)`. This 10 files are the biggest ones.

I've tried to upload maps with concurrency = 1. In that case I got stable result of 48 files loaded and 1 file not loaded. The not loaded one is the biggest (29MB).

```
Command summary:
❌ Some sourcemaps have not been uploaded correctly.
Details about the 49 found sourcemaps:
  * 48 sourcemaps successfully uploaded
  * 1 sourcemap failed to upload
done
```

**Steps to reproduce the issue:**
* Create sourcemap files of big size and try to upload them with default settings using `datadog-ci sourcemaps upload`.

**Expected behaviour:**
All files are loaded.

**Actual behaviour:**
Some of the files are not loaded.

**Additional context**
GNU/Linux x86_64
node 14.17

I believe this to be not network problem, since the result is stable. I was hoping I can work around it by turning off concurrency but it seemes not enough. Maybe the fix would be to introduce option to delay between uploads. If not, the fix must be on backend side somewhere.

**Comment by StreetStrider** [comment]
Hello.
I've got a home wifi spot, indeed, but it's pretty ok in terms of stability and speed. There're not a lot of clients and signal is good.
This is what it look like if I try use fast-cli:
```
┗ fast -u    
    40 Mbps ↓ / 8.8 Mbps ↑
```

Our goal is to run this in CI, of course. Right now I'm at local test phase. I'll try it in prod eventually, but I was troubled by the fact of the issue and the fear this would happen in real environment as well.

I've tried to remove all files except the big one, but the issue is still the same: after 5 attempts file is not loaded.

**Comment by lraucy** [comment]
Thanks for sharing these details. Your upload bandwidth might explain the 408 you receive.

The server closes the connection if the upload is not finished within 30 seconds.
An upload consist of the sourcemap + the minified file. Given your upload speed, it seems like you can only send sourcemaps up to 33MB (sourcemap and minified file together), provided you have all your bandwidth available. I think this explains the result you get.

If you move this upload to a CI job with enough upload speed, this should fix your problem.

On our side I've created a task to improve the command: ideally, it should adapt the concurrency automatically depending on the available bandwidth, and output a more helpful error message.

**Comment by StreetStrider** [comment]
Understood, thank you. So, I think, I'm clear to proceed with my work on CI's side.
