### ISSUE TITLE
datadog-ci command not exiting properly when tests are finished

### ISSUE THREAD

**Issue by blhblah1** [DataDog/datadog-ci#469]
**Describe what happened**
Every time I run the `datadog-ci synthetics run-tests` command I always have to ctrl-c to kill the command after tests are finished

**Steps to reproduce the issue:**
📝1. Execute `datadog-ci synthetics run-tests`
   2. Output:
   3. `Tests execution summary: 2 passed, 3 failed
        ^C`

**Expected behaviour:**
📝1. The command should exit gracefully when all tests are finished

**Actual behaviour:**
📝1. The command never exits

**Additional context**
 - OS version
 - Node version
 - an explanation of what might cause the bug and/or how it can be fixed

**Comment by m-rousse** [comment]
Hi @blhblah1,
Could you provide the command you ran and the configuration file going with it if any? (With API/app keys redacted)

**Comment by blhblah1** [comment]
`{
    "apiKey": "",
    "appKey": "",
    "datadogSite": "datadoghq.com",
    "files": "api.synthetics.json",
    "tunnel": true
}`

`datadog-ci synthetics run-tests`

**Comment by m-rousse** [comment]
Thanks, could you also provide with the node version you are using?
(With these, we'll work on that next week as well)

**Comment by blhblah1** [comment]
17.3.1

**Comment by m-rousse** [comment]
Hi @blhblah1,
We are still working on it, it seems to be related to one of our dependencies being incompatible with newer versions of node, we are testing a fix internally.

**Comment by m-rousse** [comment]
Hi @blhblah1,
This issue should have been fixed with #470 released in version `0.17.3`.
I'll close this issue as it is fixed, feel free to re-open in case you experience this problem again.
