### ISSUE TITLE
Use caret dependencies

### ISSUE THREAD

**Issue by noahw3** [DataDog/datadog-ci#471]
All of the dependencies for this package are pinned as exact versions. This means that any bugfixes or security vulnerability fixes for transitive dependencies that would be semver compliant cannot be adjusted in consumers. It also means that duplicate versions of the same dependency are often dragged in (see https://github.com/DataDog/datadog-ci/issues/466).

Ideally this package would use caret dependencies instead, so for example instead of `aws-sdk@2.1012.0` it would be `aws-sdk@^2.1012.0`

**Comment by Drarig29** [comment]
Closed this issue because we now use the caret `^` for all `@aws-sdk` packages. For the rest, the packages are small in size generally, so it's not urgent to unpin them. In future reviews, we'll push for `^` so we fix it little by little.
