### ISSUE TITLE
react-native support for uploading source map to datadog

### ISSUE THREAD

**Issue by nisevi** [DataDog/datadog-ci#518]
**Is your feature request related to a problem? Please describe:**
No, this is not a problem at the moment, is just a nice to have I would like to know is possible.

**Describe the solution you'd like:**
Hi there, was mentioned [here](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs#upload-your-source-maps) we can upload `dist` for having the sourcemap, but how do we achieve the same with `react-native`? 

**Additional context:**
We have a react-native app we would like to setup to have a stack trace of the errors we may face 🤖 .

**Comment by andrew-hm** [comment]
what would an example for the `--minified-path-prefix`?

**Comment by hankwz** [comment]
I tried to run the datadog-ci react-native upload command according to [here](https://github.com/DataDog/datadog-ci/tree/master/src/commands/react-native#upload), 
```
datadog-ci react-native upload --platform ios --service xxx --bundle ./temp/main.jsbundle --sourcemap ./temp/main.jsbundle.map --release-version 0.0.0-1 --build-version 1 
```
but it returns the request timeout error. 
![Screen Shot 2022-10-31 at 12 10 10 PM](https://user-images.githubusercontent.com/10568063/199091104-363bea76-b2a2-45f4-a042-7869b957bead.png)

**Comment by vkundapur** [comment]
I am able to upload the source maps without any issue. But DataDog does not show the unminified code. Is this document valid
https://github.com/DataDog/datadog-ci/tree/master/src/commands/react-native#upload

I the error like this in DataDog. I see unminification failed and it's not mapped to the source.
<img width="769" alt="image" src="https://user-images.githubusercontent.com/104626733/233384961-6bada72a-3ce0-4df3-9f64-62cfe553cb8b.png">

**Comment by vkundapur** [comment]
> Hi @vkundapur, could you share a screenshot of the result of the upload command?
> 
> If you've setup your project to automatically send sourcemaps on builds, that will be in the Android build output, under the following section:
> 
> ```
> > Task :app:uploadReleaseSourcemaps
> ```
> 
> Alternatively, you can also reach out to [our support team](https://www.datadoghq.com/support/) which will be able to assist you by looking at your particular case.

Thanks for the response. The upload is completing successfully.

![image](https://user-images.githubusercontent.com/104626733/233406015-e16aac7c-e1db-4370-9600-f79c5e239441.png)

**Comment by louiszawadzki** [comment]
Hi @vkundapur, 

Thanks for providing this screenshot. From the output I believe you're using a version from `@datadog/datadog-ci` somewhere between `2.6.0` and `2.8.0`. There's a bug in these versions that would cause the sourcemaps not to be indexed on our end on some conditions.

Could you update to version `2.8.1`, which includes a fix for this issue, and try to submit the sourcemap once again?

Let me know if you still have the issue.

**Comment by vkundapur** [comment]
> Hi @vkundapur,
> 
> Thanks for providing this screenshot. From the output I believe you're using a version from `@datadog/datadog-ci` somewhere between `2.6.0` and `2.8.0`. There's a bug in these versions that would cause the sourcemaps not to be indexed on our end on some conditions.
> 
> Could you update to version `2.8.1`, which includes a fix for this issue, and try to submit the sourcemap once again?
> 
> Let me know if you still have the issue.

Thanks @louiszawadzki. That seems to fix the issue

**Comment by louiszawadzki** [comment]
Awesome! I'm closing this issue since the original one (react-native being supported) is fixed :) 
Feel free to open a new issue if you encounter any issue with React Native sourcemaps upload!
