### ISSUE TITLE
Timestamp is ignored

### ISSUE THREAD

**Issue by janisz** [DataDog/datadog-ci#593]
**Describe what happened**
I uploaded my junit reports but all of them were marked as now timestamp information from report was ignored.

**Steps to reproduce the issue:**
Take a report with timestamp
```xml
<testsuite name="SomeTest" tests="29" skipped="0" failures="0" errors="0" timestamp="2022-06-10T00:18:53" time="80.549">
...
```
and upload it. Timestamp will be ignored and insted current time will be used.

**Expected behaviour:**
Use provided timestamp as event timestamp.

**Actual behaviour:**
Use current time.

**Comment by AdrianLC** [comment]
Hello @janisz thanks for the report! This should work as far as I know. Are you still having the issue?
If so, could you share a full XML file that is not having the timestamps loaded properly?
