### ISSUE TITLE
v1.14.0 missing semver dependency

### ISSUE THREAD

**Issue by andreasemprebon** [DataDog/datadog-ci#634]
**Describe what happened**

Installing the latest version 1.14.0 fails because `semver` is not declared as part of the dependencies.
It has been introdcued with this commit: https://github.com/DataDog/datadog-ci/commit/19eeb46ccc232e95edeb8c4abbc06d12917b87a3 in `src/commands/flutter-symbols/upload.ts`

**Steps to reproduce the issue:**

```
yarn add @datadog/datadog-ci
```

**Expected behaviour:**

The dependcy gets correctly installed

**Actual behaviour:**

```
Error: @datadog/datadog-ci tried to access semver, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Additional context**
N\A

**Comment by fuzzybinary** [comment]
Thanks for reporting!

v1.14.1 Should now be available and should fix this issue.
