### ISSUE TITLE
ERROR: authorization error when running synthetics tests

### ISSUE THREAD

**Issue by simonxuhao** [DataDog/datadog-ci#697]
The following command for manually running Datadog synthetics tests had always worked:

`$ datadog-ci synthetics run-tests --config synthetic_tests.json`

 until recently, now it fails with the following error:

```
[DEPRECATED] "files" should be an array of string instead of a string.
Finding files in /tmp/workspace/{,!(node_modules)/**/}*.synthetics.json

Got test files:
  - src/socialTests/deploymentVerification/test1.synthetics.json
  - src/socialTests/deploymentVerification/test2.synthetics.json
  - src/socialTests/deploymentVerification/test3.synthetics.json
  - src/socialTests/deploymentVerification/test4.synthetics.json


ERROR: authorization error 
Failed to get test: query on https://api.datadoghq.com/api/v1/synthetics/tests/xxx-xxx-xxx returned: "Forbidden"

Credentials refused, make sure `apiKey`, `appKey` and `datadogSite` are correct.
Because `failOnCriticalErrors` is not set or disabled, the command will exit with an error code 0. Use `failOnCriticalErrors: true` to exit with an error code 1.
```

Same failure with 1.16.0, 1.17.0 and 2.0.0, however, with 1.16.0 the error message is

```
ERROR: authorization error 
Request failed with status code 403
```

I don't understand why because nothing changed on our side, did anything change on the Datadog server side?

Thanks

**Comment by m-rousse** [comment]
Hi @simonxuhao,
No update was released regarding this endpoint recently.
Could you make sure your API/App keys are valid?
- [Page to list API keys](https://app.datadoghq.com/organization-settings/api-keys)
- [Page to list application keys](https://app.datadoghq.com/organization-settings/application-keys)

**Comment by simonxuhao** [comment]
App key error, sorry for the hassle.
