### ISSUE TITLE
Yarn audit High : minimatch from glob dependencies

### ISSUE THREAD

**Issue by ellisium** [DataDog/datadog-ci#701]
Please update your glob dependency to fix minimatch version

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ minimatch ReDoS vulnerability                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.5                                                      │
├───────────────┼───────────────────────────────────────────
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │  @datadog/datadog-ci > glob > minimatch       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1084765

**Comment by lefebvree** [comment]
Hello @ellisium, this has been addressed in https://github.com/DataDog/datadog-ci/pull/702 and released with v`2.1.0`.
