### ISSUE TITLE
NodeJS 18 support

### ISSUE THREAD

**Issue by ESalih-Dev** [DataDog/datadog-ci#719]
**Describe what happened**

I'm attempting to upgrade our AWS Lambda runtime from Node 16 to Node 18. We're using `datadog-ci` in order to apply [datadog-lambda-js](https://github.com/DataDog/datadog-lambda-js) and [datadog-lambda-extension](https://github.com/DataDog/datadog-lambda-extension). Datadog Lambda JS received NodeJS 18 support as part of [v85 release](https://github.com/DataDog/datadog-lambda-js/releases). `datadog-ci` however does not yet support Node 18 layers ([see here](https://github.com/DataDog/datadog-ci/blob/ec5a7c970a98d9f696e4f9a3490a1fded5d737ab/src/commands/lambda/constants.ts)).

Have tested manually applying the layers in the UI and they are successful.

**Steps to reproduce the issue:**

- In GHA execute `datadog-ci lambda instrument <omitted> -v 85 -e 35` for a Lambda running Node18

**Expected behaviour:**

Should be able to successfully apply Datadog layer.

**Actual behaviour:**

<img width="1245" alt="Untitled" src="https://user-images.githubusercontent.com/24623058/206430892-37c952b2-f5e7-4d0d-a420-c340e652815d.png">

**Additional context**
 - OS version
 - Node version 
 18
 - an explanation of what might cause the bug and/or how it can be fixed
 
We require Node 18 support in DataDog CI - [code link](https://github.com/DataDog/datadog-ci/blob/ec5a7c970a98d9f696e4f9a3490a1fded5d737ab/src/commands/lambda/constants.ts).

**Comment by duncanista** [comment]
Thank you for raising this issue! 🙏🏽
