### ISSUE TITLE
Lambda Instrument is failing with "Local git repository is dirty"

### ISSUE THREAD

**Issue by luisabtrace** [DataDog/datadog-ci#751]
`lambda instrument` is failing with

```
Error:  Error: Local git repository is dirty
Error: Process completed with exit code 1.
```

This happened on multiple repositories and seems to have started in the last few days.

**Steps to reproduce the issue:**

This is the command we're running:

```
npx @datadog/datadog-ci lambda instrument \
            --functions-regex "website.*-prod" \
            -r ${{ secrets.PROD_REGION }} \
            -v 58 \
            -e 22 \
            --service website \
            --env prod
```

**Expected behaviour:**

Command should succeed and functions should be instrumented.

**Actual behaviour:**

Command fails with:

```
Error:  Error: Local git repository is dirty
Error: Process completed with exit code 1.
```

**Additional context**

This is happening on GitHub Actions. The pipeline itself didn't change, so I don't think there is a reason for it to think the "local git repository is dirty".

**Comment by ESalih-Dev** [comment]
I'm also having currently experiencing this issue though noticed it only seems to occur on our `main` branch 🤔

**Comment by LevBuchel** [comment]
We are having the same issue

**Comment by luisabtrace** [comment]
I found that passing `--no-source-code-integration` fixes the issue. Source code integration used to be disabled by default but has been enabled recently.

On further thought, it's possible that this is not a real bug, it's just we might be doing something in the pipeline that causes the repository to become dirty. Would need to investigate.
