### ISSUE TITLE
Error About AWS SDK v2 When Uploading Sourcemaps

### ISSUE THREAD

**Issue by brekt** [DataDog/datadog-ci#776]
### Bug description

We started seeing this error today when we run `npx @datadog/datadog-ci sourcemaps upload...` in our CI pipeline:

```
Error: (node:467) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Describe what you expected

I expected successful upload of sourcemaps to Datadog.

### Steps to reproduce the issue

run `npx @datadog/datadog-ci` with the parameters as you normally do.

### Additional context

Jenkins / Linux
Node 16.13.1
pnpm although we invoke @datadog/datadog-ci with npx

### Command

sourcemaps

**Comment by brekt** [comment]
Just want to clarify that this is actually throwing an error, not just logging a warning.

**Comment by sawilde** [comment]
I believe it is a warning (I don't see the text `Error:` in my logs but it does look like you have some refactoring to do.

```
  [2023-02-21T06:08:26Z] (node:35) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
  | [2023-02-21T06:08:26Z]
  | [2023-02-21T06:08:26Z] Please migrate your code to use AWS SDK for JavaScript (v3).
  | [2023-02-21T06:08:26Z] For more information, check the migration guide at https://a.co/7PzMCcy
  | [2023-02-21T06:08:26Z] (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by brekt** [comment]
I've been investigating this and it's definitely an error in our pipeline, not just a warning. It's caught directly with a try / catch or without that it bubbles up to an `unhandledRejection` listener.

Adding `--trace-warnings` led me to this commit from about two weeks ago: https://github.com/aws/aws-sdk-js/commit/1477fdbd020c40bbfda08ed7182e11eb5fee4803

According to that code it looks like you could disable that function by adding
```js
 require('aws-sdk/lib/maintenance_mode_message').suppress = true;
 ```
in the @datadog/datadog-ci library.

I'd be happy to test that out on a beta version.

I'm going to look into testing this with a different version of Node as well, although just upgrading Node isn't a trivial solution for us currently.

**Comment by brekt** [comment]
After investigating a little further I found that we had an abstraction around the code that was executing the upload command that was listening to stderr and throwing when it encountered anything. Node's process warnings go through stderr so our pipeline was throwing the warning.

Closing this ticket.
