### ISSUE TITLE
Exec format error on Ubuntu 18.04 ARM64

### ISSUE THREAD

**Issue by adamsummerville** [DataDog/datadog-ci#821]
### Bug description

Hello, I cannot set up ` datadog-ci `on Ubuntu 18.04 ARM64 AWS t4g.nano instance.   

![Screenshot 2023-04-05 at 2 03 24 PM](https://user-images.githubusercontent.com/95311009/230165459-0348f28e-5341-4cf6-b206-192755400485.png)

ERROR: cannot execute binary file: Exec format error

### Describe what you expected

This setup is part of our normal build on Ubuntu 18.04 and works fine on x86_64 versions.   

### Steps to reproduce the issue

```
curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "./datadog-ci"
sudo mv ./datadog-ci /usr/local/bin/datadog-ci
chmod +x /usr/local/bin/datadog-ci
datadog-ci version
```

### Additional context

AWS EC2:
AMI - ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-20230215
INSTANCE  - t4g.nano

### Command

None

**Comment by jgao54** [comment]
+1

Work around with `npm install`.

It looks like the release asset does not include a linux_arm binary. would be awesome to publish it for future releases.

**Comment by Drarig29** [comment]
Hi @adamsummerville! We now provide ARM binaries for Ubuntu.

You can download it with:

```bash
curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-arm64" --output "./datadog-ci"
```
