### ISSUE TITLE
Invalid documentation for pubspec location

### ISSUE THREAD

**Issue by r3nic1e** [DataDog/datadog-ci#844]
`datadog-ci flutter-symbols upload --pubspec-location ../pubspec.yaml` provides following error:
```
Unknown Syntax Error: Unsupported option name ("--pubspec-location").
```

Readme for the command references `--pubspec-location` flag - https://github.com/DataDog/datadog-ci/blob/master/src/commands/flutter-symbols/README.md
While the code uses `--pubspec` flag - https://github.com/DataDog/datadog-ci/blob/master/src/commands/flutter-symbols/upload.ts#L472

Probably it's better to update documentation to not break backward compatibility.

I can make a PR to fix that if that's applicable.

**Comment by fuzzybinary** [comment]
Hi @r3nic1e thanks for reporting.

I agree, I'd rather update the documentation than break compatibility. I'll submit a PR momentarily.

Thanks!
