### ISSUE TITLE
Improve error reporting of datadog-ci metrics command

### ISSUE THREAD

**Issue by kombucha** [DataDog/datadog-ci#856]
### Feature request description

I'm trying to upload metrics at the pipeline level using a command that looks like this:

```sh
npx "@datadog/datadog-ci@^2" metric --level pipeline --metrics foo:1 bar:2 # and so on
```

I was batching a few (~30-40) metrics together in one call and got the following error:

```
Could not send metrics: Request failed with status code 400
```

Which is not really actionable...
By modifying the error handling here to access the response body:
https://github.com/DataDog/datadog-ci/blob/54325a31082f804422c040382a0470b057609868/src/commands/metric/metric.ts#L133-L137

I was able to get a more specific error from the API
```
"API input validation failed: {'metrics': ['Length must be between 1 and 20.']}"
```

Which helped me understand and chunk my metrics array accordingly.
I'm still getting a 400 after the first few batches though, with the following error:
```
{ errors: [ 'Validation failed for input.' ] }
```

Which once again, is not actionable...
The endpoint used, `api/v2/ci/pipeline/metrics`, doesn't seem to be [documented](https://docs.datadoghq.com/api/latest/ci-visibility-pipelines/) (or at least I could find the documentation)

### Solution

On the client side, it would be helpful to leverage the error message returned by the API.
On the API side (although I don't know if the maintainers of this library also maintain the API 😄 ), documentation or more actionable error messages would help a great deal 🙏 

### Command

metric

**Comment by mariahrucker** [comment]
Based on my understanding of your issue, you need to set up the pytest test runner to produce JUnit XML reports that can be interpreted by the DataDog dashboard for test outcomes. To enable `pytest` to create JUnit XML reports that can be parsed by the DataDog dashboard, you will need to install the `pytest-datadog` plugin and configure it with custom settings. 

1. Install the `pytest-datadog` plugin.
2. Set the `--junitxml` option to specify the path where you want to save the JUnit XML report, and use the `--dd-tags`, `--dd-service`, `--dd-test-plan`, and `--dd-custom-tags` options to configure the `Datadog` plugin. For example:

   ```
   pytest --junitxml=path/to/report.xml --dd-tags=env:dev --dd-service=my-service --dd-test-plan=my-plan --dd-custom-tags=tag1:value1,tag2:value2
   ```

Replace `path/to/report.xml` with the path where you want to save the JUnit XML report.
   
3. After the tests have run, verify that the JUnit XML report has been generated in the specified path.
4. In the DataDog dashboard, go to the Integrations page and search for the `junit` integration.
5. Click on the `Configuration` tab and provide the path to the JUnit XML report in the `Path to test results file` field.
6. Save the configuration and run the integration.
