### ISSUE TITLE
Synthetics: print link to summary at the beginning of execution

### ISSUE THREAD

**Issue by drmaciej** [DataDog/datadog-ci#864]
### Feature request description

As of right now, in v2.10.0, found tests are printed right away, and then a message like "Waiting for 5 test results". There's not much in terms of progress indication, which in itself would be a great feature. A quick win would be to print the link to the CI batch run (`View full summary in Datadog:`) at the beginning of execution as well as at the end.

### Command

synthetics

**Comment by Drarig29** [comment]
Hey @drmaciej!

That's an excellent idea! Initially we printed the link at the end of the summary as it's easier to reach once the CI job is done, but we didn't consider the case where we are waiting for the jobs to finish. We added a card in our backlog to tackle that as soon as possible.

Thanks for submitting this issue :pray:
