### ISSUE TITLE
Support sourcemaps with arbitrary host

### ISSUE THREAD

**Issue by marians** [DataDog/datadog-ci#89]
**Is your feature request related to a problem? Please describe:**

The `datadoc-ci sourcemaps upload` command requires a `--minified-path-prefix` flag. This means during the sourcemap upload it has to be known under which host name(s) the source can be accessed later.

This does not fit our use case well, since we run our web application under many different URLs / on many different hosts.

**Describe the solution you'd like:**

Ideally, only the service name, version, and path should suffice as matching criteria. We have only one service configured. If then the path matches e. g. `/assets/main.9443b096252b.js.map`, datadog should be able to match the request with our uploaded source.

**Describe alternatives you've considered:**

Uploading all sourcemaps dozens of times, each time with a different `--minified-path-prefix`.

**Additional context:**

n/a

**Comment by lraucy** [comment]
Hi @marians!

Indeed the current API is is not great for users serving their JS from multiple domains. As you described it, it's possible to work around that by uploading the sourcemaps once per domain, but it's annoying & suboptimal at best, and simply impossible when domains/URL prefixes are dynamically generated.

That's definitely a use case we want to better support, and we'll be working on that soon.

**Comment by jybp** [comment]
Hey @marians !

Using the new [0.9.0](https://github.com/DataDog/datadog-ci/releases/tag/v0.9.0) version you can now omit the host from the `--minified-path-prefix` flag. Note that you still have to make sure that it resolves to the correct absolute URL path.

Please refer to the updated [documentation](https://github.com/DataDog/datadog-ci/tree/v0.9.0/src/commands/sourcemaps#upload) on that flag.

**Comment by praxxis** [comment]
@marians were you able to get arbitrary hosts working with the 0.9 version? I have the same use case and currently can't get it working - sourcemaps are not recognized with `minified-path-prefix` set to `/`, but they are with explicit hosts. I'm unsure if the problem is on my end at this point.

**Comment by marians** [comment]
No, haven't tried

**Comment by jybp** [comment]
@praxxis Thanks for leaving a comment. Could you please contact the Datadog support so we can dig deeper into your issue?
