### ISSUE TITLE
[Vulnerabilities] - fast-xml-parser vulnerabilities fixed by @aws-sdk

### ISSUE THREAD

**Issue by mbriand-lucca** [DataDog/datadog-ci#914]
### Bug description

When I launched a `npm ci`, I found 9 vulnerabilities caused by `fast-xml-parser` used in `@aws-sdk/**` modules.

### Describe what you expected

It will be nice to upgrade to `v3.347.1` for `@aws-sdk/**` modules to get this fix about this vulnerability.

### Command

`npm ci`

**Comment by fdoe** [comment]
This is the underlying [CVE report](https://github.com/advisories/GHSA-6w63-h3fj-q4vw) for fast-xml-parser.

**Comment by JeanBeaurepaire** [comment]
#https://github.com/DataDog/datadog-ci/pull/913 #
