### ISSUE TITLE
Error: Cannot find module '@aws-sdk/property-provider' on npx @datadog/datadog-ci@2.16.0

### ISSUE THREAD

**Issue by kien-cs** [DataDog/datadog-ci#948]
### Bug description

When I run: 
`npx @datadog/datadog-ci`

I get the following error: 
```
➜  /tmp npx @datadog/datadog-ci
Need to install the following packages:
  @datadog/datadog-ci@2.16.0
Ok to proceed? (y) y
Error: Cannot find module '@aws-sdk/property-provider'
Require stack:
- /Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/functions/commons.js
- /Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/instrument.js
- /Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/cli.js
- /Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/functions/commons.js:37:29)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/functions/commons.js',
    '/Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/instrument.js',
    '/Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/commands/lambda/cli.js',
    '/Users/kien/.npm/_npx/2c8d683be5ffbe89/node_modules/@datadog/datadog-ci/dist/cli.js'
  ]
}
➜  /tmp
```

### Describe what you expected

Installed latest version correctly

### Steps to reproduce the issue

cd /tmp
npx @datadog/datadog-ci

### Command

None

**Comment by kien-cs** [comment]
@duncanista Looks like the issue introduced in this commit here: https://github.com/DataDog/datadog-ci/commit/e71bf67110a7ec3feab2eb6a441e229d8c73a69a

Can you please help see if my PR would fix this issue? Thanks!
https://github.com/DataDog/datadog-ci/pull/949

**Comment by kien-cs** [comment]
Confirmed that the issue start showing up on: `v2.11.0`

npx @datadog/datadog-ci@2.10.0 - works
npx @datadog/datadog-ci@2.11.0 - Error: Cannot find module '@aws-sdk/property-provider'

**Comment by chrismo** [comment]
this just hit our CI process within the last hour as well

**Comment by kien-cs** [comment]
thanks for confirming @chrismo , currently we lock this at the known working version in our package.json

```
"@datadog/datadog-ci": "2.10.0",
```

**Comment by duncanista** [comment]
Hey @kien-cs, thank you so much for reporting.

I wonder why this didn't fail when the credentials provider was introduced. I'll look into it.

**Comment by flowjo-lukej** [comment]
AWS moved a bunch of their packages over to the `@smithy` namespace. Their latest @aws-sdk bundle does not include `@aws-sdk/property-provider`. Changing this import to `@smithy/property-provider` might be the way here.

**Comment by dannykansas** [comment]
Just hit our CI pipelines in a few spots; thanks for filing this issue. Pinning dep to `2.10.x` recommended

**Comment by acook-vhs** [comment]
Confirming this issue as well, Looking forward to a fix!

**Comment by fasani-tx** [comment]
+1 for me :)

**Comment by marcel-olaru** [comment]
had the same issue this morning in our pipelines, pinned version `2.10.x` fixed it for now

**Comment by skamarakas** [comment]
the problem still exists in the latest stable version 😞

**Comment by Romain7495** [comment]
+1 we still have the issue.
To fix, add manually the missing package `npm install -g @aws-sdk/property-provider`
