### ISSUE TITLE
Allow datadog-ci CLI to execute tunneled multi-step API tests

### ISSUE THREAD

**Issue by blhblah1** [DataDog/datadog-ci#959]
### Feature request description

It seems that since v2.3.0 the datadog-ci CLI tool will not execute tunneled multi-step API tests whereas v2.2.0 would. This functionality is breaking the majority of my tests and I need a resolution or update to include this functionality again.

### Command

synthetics

**Comment by Drarig29** [comment]
Hey @blhblah1!

At the time of that version, we didn't have support for tunneled multi-step API tests so we made datadog-ci fail if you were trying to do this (https://github.com/DataDog/datadog-ci/pull/734).

We now have support for tunneled **HTTP steps** of multi-step API tests, so we added a card in our backlog to allow this.

Thanks for reporting this issue. 🙏

**Comment by blhblah1** [comment]
If I wanted to run a local copy with the functionality restored can I just remove the check for the test type?

**Comment by Drarig29** [comment]
You said that `v2.2.0` is working for you. What makes you want to use the latest version exactly? We planned to fix this next week.

**Comment by blhblah1** [comment]
There is a vulnerability for simple-git with 2.2.0: https://security.snyk.io/vuln/SNYK-JS-SIMPLEGIT-2421199

**Comment by Drarig29** [comment]
Hey @blhblah1! The related PR should be released this week.
