### ISSUE TITLE
vm2 discontinued, critical vulnerability still exists, used in 2.17.1

### ISSUE THREAD

**Issue by spacejamjim** [DataDog/datadog-ci#988]
### Bug description

https://github.com/patriksimek/vm2 is discontinued but is a [critical security threat](https://github.com/advisories/GHSA-cchq-frgv-rjh5) and used in 2.17.1

Path: @datadog/datadog-ci > proxy-agent > pac-proxy-agent > pac-resolver > degenerator > vm2
The [issue is being tracked](https://github.com/TooTallNate/proxy-agents/issues/218) in the proxy-agents repo. 

### Describe what you expected

Relies on dependencies being updated, link to tracked issue above. In short, vm2 recommends moving to https://www.npmjs.com/package/isolated-vm though the proxy-agents dependency has an alternative solution yet to be implemented.

### Command

None

**Comment by lefebvree** [comment]
Hello @spacejamjim, the release 2.17.2 has been published and removes the vm2 dependency.
