### ISSUE TITLE
vm2@3.9.19 is deprecated

### ISSUE THREAD

**Issue by blhblah1** [DataDog/datadog-ci#990]
### Bug description

Please update the vm2 package or switch to isolated-vm

`+ npm install -g @datadog/datadog-ci
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
added 295 packages in 6s`

### Command

synthetics

**Comment by lefebvree** [comment]
Hello @blhblah1, the release 2.17.2 has been published and removes the vm2 dependency.
