### ISSUE TITLE
@Nested JUnit classes fail upload

### ISSUE THREAD

**Issue by jtylock** [DataDog/datadog-ci#992]
### Bug description

```❌ Failed upload jUnitXML for [example-path$NestedClassName.xml]: Error: Request failed with status code 400```

The filename sanitization [HERE in v2.17.1](https://github.com/DataDog/datadog-ci/pull/984/files#diff-b8e4cc2eb97217ec2cf3b8bb8447ea1a9e2409e98003b589d8e80290ff4b71acR6) breaks the upload for JUnit tests with Nested annotations.

Example class this impacts:
```
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ExampleTest(
) {

    @Test // some tests here


    @Nested
    @DisplayName("Also test this")
    @TestInstance(TestInstance.Lifecycle.PER_CLASS)
    inner class AlsoTestThis {

        @Test // some more tests here
    }
}
```

### Describe what you expected

These test classes should still be able to upload to DataDog. We've pinned to v2.16.1 as a workaround for now.

### Steps to reproduce the issue

1. Have a JUnit test with a Nested test class
2. `./gradlew test`
3. `datadog-ci junit upload --service ${{ inputs.service-name }} ${{ inputs.test-report-path }}`

### Command

junit

**Comment by juan-fernandez** [comment]
hey! Thanks for the report. This should hopefully be fixed with https://github.com/DataDog/datadog-ci/pull/987 😄 . 

In the meantime, you should be able to install [v2.16.1](https://github.com/DataDog/datadog-ci/releases/tag/v2.16.1), which should not have the bug
